import {StyleSheet} from 'react-native';
import {navigationPrimaryColor} from '../../theme/variables';

export default StyleSheet.create({
  RedeemWrapper: {
    backgroundColor: navigationPrimaryColor,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  RedeemTitle: {
    color: '#000C2E',
    // fontFamily: 'Tungsten-Bold',
    textTransform: 'uppercase',
    fontSize: 32,
    fontWeight: 'bold',
    letterSpacing: 1,
    textAlign: 'center',
    lineHeight: 32,
    marginTop: 0,
    marginBottom: 12,
  },
  RedeemSubTitle: {
    color: '#000C2E',
    // fontFamily: 'Tungsten-Bold',
    // textTransform: 'uppercase',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0,
    textAlign: 'center',
    lineHeight: 19,
    marginTop: 0,
    marginBottom: 5,
  },
  RedeemInnerWrap: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    padding: 15,
    width: '100%',
    position: 'relative',
  },
  RedeemBox: {
    flex: 1,
    flexGrow: 1,
    minHeight: 215,
    marginTop: 12,
    marginBottom: 12,
    marginRight: 0,
    marginLeft: 0,
  },
  RedeemBackgroundBox: {
    width: '100%',
    height: '100%',
  },
  RedeemDecoration: {
    position: 'absolute',
    top: -20,
    right: 20,
    height: 100,
    width: 100,
    resizeMode: 'contain',
  },
  RedeemOneBoxInnerWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingRight: 20,
    paddingLeft: 20,
    paddingTop: 30,
    paddingBottom: 30,
  },
  RedeemOneBoxHeading: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    letterSpacing: 1.2,
    lineHeight: 29,
    textTransform: 'uppercase',
    padding: 0,
    margin: 0,
  },
  RedeemOneBoxSubheading: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '300',
    letterSpacing: 0,
    lineHeight: 16,
  },
});
