export const avatarAssets = {
  Catalog: [
    {
      ItemId: 'frankenstein',
      ItemClass: 'monster',
      CatalogVersion: 'Monsters',
      DisplayName: 'Frankenstein',
      VirtualCurrencyPrices: {},
      Tags: ['monsters'],
      CustomData: '{"availableClothes":"2"}',
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'eyes-one',
      ItemClass: 'eyes',
      CatalogVersion: 'Monsters',
      DisplayName: 'Eyes With Frame',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'eyes-two',
      ItemClass: 'eyes',
      CatalogVersion: 'Monsters',
      DisplayName: 'Pair of eyes',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'head-one',
      ItemClass: 'head',
      CatalogVersion: 'Monsters',
      DisplayName: 'Hat',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'mouth-one',
      ItemClass: 'mouth',
      CatalogVersion: 'Monsters',
      DisplayName: 'Tongue Out',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'mouth-two',
      ItemClass: 'mouth',
      CatalogVersion: 'Monsters',
      DisplayName: 'Lower front teeth',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'nose-one',
      ItemClass: 'nose',
      CatalogVersion: 'Monsters',
      DisplayName: 'Round shaped nose',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'nose-two',
      ItemClass: 'nose',
      CatalogVersion: 'Monsters',
      DisplayName: 'Nostrils',
      VirtualCurrencyPrices: {},
      Tags: [],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
  ],
};
