export const doorAsset = {
  Catalog: [
    {
      ItemId: 'deco_g1_boards',
      ItemClass: 'decoration',
      CatalogVersion: 'Doors',
      DisplayName: 'Boards',
      VirtualCurrencyPrices: {},
      Tags: ['group1Decorations'],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'deco_g1_spray_paint',
      ItemClass: 'decoration',
      CatalogVersion: 'Doors',
      DisplayName: 'Spray Paint',
      VirtualCurrencyPrices: {},
      Tags: ['group1Decorations'],
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'door_basic',
      ItemClass: 'door',
      CatalogVersion: 'Doors',
      DisplayName: 'Basic Door',
      VirtualCurrencyPrices: {},
      Tags: [],
      CustomData: '{"defaultColor":"#FF0000"}',
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
    {
      ItemId: 'door_decorative',
      ItemClass: 'door',
      CatalogVersion: 'Doors',
      DisplayName: 'Decorative Door',
      VirtualCurrencyPrices: {},
      Tags: [],
      CustomData: '{"defaultColor":"#FF0000"}',
      Consumable: {},
      CanBecomeCharacter: false,
      IsStackable: false,
      IsTradable: false,
      IsLimitedEdition: false,
      InitialLimitedEditionCount: 0,
    },
  ],
};

export const saveDoorPayload = {
  Data: {
    selectedColor: '#ff0',
    selectedDoorId: 'door_basic',
    selectedGroupOneDecorations: ['deco_g1_boards', 'deco_g1_spray_paint'],
  },
};
